// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi(in *jlexer.Lexer, out *UserRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "namespace_id":
			out.NamespaceID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi(out *jwriter.Writer, in UserRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"namespace_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.NamespaceID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi1(in *jlexer.Lexer, out *UserOrgRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			out.UserID = int64(in.Int64())
		case "org_id":
			out.OrgID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi1(out *jwriter.Writer, in UserOrgRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"org_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.OrgID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserOrgRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserOrgRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserOrgRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserOrgRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi1(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi2(in *jlexer.Lexer, out *UserHandlerCreation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "password":
			out.Password = string(in.String())
		case "namespace_id":
			out.NamespaceID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi2(out *jwriter.Writer, in UserHandlerCreation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"namespace_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.NamespaceID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserHandlerCreation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserHandlerCreation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserHandlerCreation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserHandlerCreation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi2(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi3(in *jlexer.Lexer, out *UserGroupRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			out.UserID = int64(in.Int64())
		case "group_id":
			out.GroupID = int64(in.Int64())
		case "namespace_id":
			out.NamespaceID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi3(out *jwriter.Writer, in UserGroupRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"group_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.GroupID))
	}
	{
		const prefix string = ",\"namespace_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.NamespaceID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserGroupRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserGroupRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserGroupRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserGroupRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi3(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi4(in *jlexer.Lexer, out *RefreshTokenRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "username":
			out.Username = string(in.String())
		case "password":
			out.Password = string(in.String())
		case "namespace":
			out.Namespace = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi4(out *jwriter.Writer, in RefreshTokenRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"namespace\":"
		out.RawString(prefix)
		out.String(string(in.Namespace))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RefreshTokenRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RefreshTokenRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RefreshTokenRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RefreshTokenRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi4(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi5(in *jlexer.Lexer, out *NonAdminUsersRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "username":
			out.Username = string(in.String())
		case "namespace_id":
			out.NamespaceID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi5(out *jwriter.Writer, in NonAdminUsersRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"namespace_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.NamespaceID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NonAdminUsersRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NonAdminUsersRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NonAdminUsersRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NonAdminUsersRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi5(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi6(in *jlexer.Lexer, out *NamespaceTokenMaxTTLRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "max_ttl":
			out.MaxTTL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi6(out *jwriter.Writer, in NamespaceTokenMaxTTLRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"max_ttl\":"
		out.RawString(prefix)
		out.String(string(in.MaxTTL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NamespaceTokenMaxTTLRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NamespaceTokenMaxTTLRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NamespaceTokenMaxTTLRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NamespaceTokenMaxTTLRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi6(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi7(in *jlexer.Lexer, out *NamespaceRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "namespace":
			out.Namespace = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi7(out *jwriter.Writer, in NamespaceRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"namespace\":"
		out.RawString(prefix[1:])
		out.String(string(in.Namespace))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NamespaceRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NamespaceRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NamespaceRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NamespaceRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi7(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi8(in *jlexer.Lexer, out *NamespaceRefreshTokenMaxTTLRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "refresh_max_ttl":
			out.RefreshMaxTTL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi8(out *jwriter.Writer, in NamespaceRefreshTokenMaxTTLRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"refresh_max_ttl\":"
		out.RawString(prefix)
		out.String(string(in.RefreshMaxTTL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NamespaceRefreshTokenMaxTTLRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NamespaceRefreshTokenMaxTTLRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NamespaceRefreshTokenMaxTTLRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NamespaceRefreshTokenMaxTTLRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi8(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi9(in *jlexer.Lexer, out *NamespaceCreation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "max_ttl":
			out.MaxTTL = string(in.String())
		case "refresh_max_ttl":
			out.RefreshMaxTTL = string(in.String())
		case "enable_endpoint":
			out.EnableEndpoint = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi9(out *jwriter.Writer, in NamespaceCreation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"max_ttl\":"
		out.RawString(prefix)
		out.String(string(in.MaxTTL))
	}
	{
		const prefix string = ",\"refresh_max_ttl\":"
		out.RawString(prefix)
		out.String(string(in.RefreshMaxTTL))
	}
	{
		const prefix string = ",\"enable_endpoint\":"
		out.RawString(prefix)
		out.Bool(bool(in.EnableEndpoint))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NamespaceCreation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NamespaceCreation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NamespaceCreation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NamespaceCreation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi9(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi10(in *jlexer.Lexer, out *NameRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi10(out *jwriter.Writer, in NameRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NameRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NameRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NameRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NameRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi10(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi11(in *jlexer.Lexer, out *LoginRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "username":
			out.Username = string(in.String())
		case "password":
			out.Password = string(in.String())
		case "namespace":
			out.Namespace = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi11(out *jwriter.Writer, in LoginRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"namespace\":"
		out.RawString(prefix)
		out.String(string(in.Namespace))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoginRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoginRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoginRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoginRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi11(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi12(in *jlexer.Lexer, out *InfoRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi12(out *jwriter.Writer, in InfoRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InfoRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InfoRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InfoRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InfoRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi12(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi13(in *jlexer.Lexer, out *GroupCreation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "namespace_id":
			out.NamespaceID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi13(out *jwriter.Writer, in GroupCreation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"namespace_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.NamespaceID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GroupCreation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GroupCreation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GroupCreation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GroupCreation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi13(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi14(in *jlexer.Lexer, out *Availability) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "enable":
			out.Enable = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi14(out *jwriter.Writer, in Availability) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"enable\":"
		out.RawString(prefix)
		out.Bool(bool(in.Enable))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Availability) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Availability) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Availability) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Availability) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi14(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi15(in *jlexer.Lexer, out *AdministratorsCreation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_i_ds":
			if in.IsNull() {
				in.Skip()
				out.UserIDs = nil
			} else {
				in.Delim('[')
				if out.UserIDs == nil {
					if !in.IsDelim(']') {
						out.UserIDs = make([]int64, 0, 8)
					} else {
						out.UserIDs = []int64{}
					}
				} else {
					out.UserIDs = (out.UserIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int64
					v1 = int64(in.Int64())
					out.UserIDs = append(out.UserIDs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "namespace_id":
			out.NamespaceID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi15(out *jwriter.Writer, in AdministratorsCreation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_i_ds\":"
		out.RawString(prefix[1:])
		if in.UserIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.UserIDs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"namespace_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.NamespaceID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdministratorsCreation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdministratorsCreation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdministratorsCreation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdministratorsCreation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi15(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi16(in *jlexer.Lexer, out *AdministratorDeletion) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			out.UserID = int64(in.Int64())
		case "namespace_id":
			out.NamespaceID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi16(out *jwriter.Writer, in AdministratorDeletion) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"namespace_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.NamespaceID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdministratorDeletion) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdministratorDeletion) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdministratorDeletion) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdministratorDeletion) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi16(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi17(in *jlexer.Lexer, out *AdminAccessTokenRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "refresh_token":
			out.RefreshToken = string(in.String())
		case "namespace":
			out.Namespace = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi17(out *jwriter.Writer, in AdminAccessTokenRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"refresh_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.RefreshToken))
	}
	{
		const prefix string = ",\"namespace\":"
		out.RawString(prefix)
		out.String(string(in.Namespace))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdminAccessTokenRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdminAccessTokenRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdminAccessTokenRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdminAccessTokenRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi17(l, v)
}
func easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi18(in *jlexer.Lexer, out *AccessTokenRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "refresh_token":
			out.RefreshToken = string(in.String())
		case "namespace":
			out.Namespace = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi18(out *jwriter.Writer, in AccessTokenRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"refresh_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.RefreshToken))
	}
	{
		const prefix string = ",\"namespace\":"
		out.RawString(prefix)
		out.String(string(in.Namespace))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccessTokenRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi18(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccessTokenRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c0420e7EncodeGithubComTealFinanceQuidQuidlibServerApi18(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccessTokenRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi18(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccessTokenRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c0420e7DecodeGithubComTealFinanceQuidQuidlibServerApi18(l, v)
}
