// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ApidocsList: typeof import('./src/components/ApidocsList.vue')['default']
    'ApidocsList copy': typeof import('./src/components/ApidocsList copy.vue')['default']
    ClientList: typeof import('./src/components/ClientList.vue')['default']
    ExamplesList: typeof import('./src/components/ExamplesList.vue')['default']
    'IEva:arrowBackOutline': typeof import('~icons/eva/arrow-back-outline')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    ServerList: typeof import('./src/components/ServerList.vue')['default']
    'ServerList copy': typeof import('./src/components/ServerList copy.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}

export { }
