// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/widgets/ActionButton.vue')['default']
    AddAdmin: typeof import('./src/components/admin/add/AddAdmin.vue')['default']
    AddGroup: typeof import('./src/components/group/AddGroup.vue')['default']
    AddNamespace: typeof import('./src/components/namespace/AddNamespace.vue')['default']
    AddOrg: typeof import('./src/components/org/AddOrg.vue')['default']
    AddUser: typeof import('./src/components/user/AddUser.vue')['default']
    AddUserIntoGroup: typeof import('./src/components/user/AddUserIntoGroup.vue')['default']
    AdminDatatable: typeof import('./src/components/admin/AdminDatatable.vue')['default']
    CardsGrid: typeof import('./src/components/widgets/cards/CardsGrid.vue')['default']
    EditTokenTtl: typeof import('./src/components/namespace/EditTokenTtl.vue')['default']
    GroupDatatable: typeof import('./src/components/group/GroupDatatable.vue')['default']
    'IAntDesign:saveOutlined': typeof import('~icons/ant-design/save-outlined')['default']
    'ICi:checkBold': typeof import('~icons/ci/check-bold')['default']
    IClaritySettingsLine: typeof import('~icons/clarity/settings-line')['default']
    'IEosIcons:loading': typeof import('~icons/eos-icons/loading')['default']
    'IEosIcons:namespace': typeof import('~icons/eos-icons/namespace')['default']
    'IEp:closeBold': typeof import('~icons/ep/close-bold')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    IFluentSettings32Regular: typeof import('~icons/fluent/settings32-regular')['default']
    'IFontisto:close': typeof import('~icons/fontisto/close')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    'ILineMd:cancel': typeof import('~icons/line-md/cancel')['default']
    'IMdi:clockEditOutline': typeof import('~icons/mdi/clock-edit-outline')['default']
    'IMdi:clockOutline': typeof import('~icons/mdi/clock-outline')['default']
    'ISiGlyph:signOut': typeof import('~icons/si-glyph/sign-out')['default']
    LoadingIndicator: typeof import('./src/components/widgets/LoadingIndicator.vue')['default']
    NamespaceDatatable: typeof import('./src/components/namespace/NamespaceDatatable.vue')['default']
    NamespaceInfo: typeof import('./src/components/namespace/NamespaceInfo.vue')['default']
    NamespaceSelector: typeof import('./src/components/namespace/NamespaceSelector.vue')['default']
    OrgDatatable: typeof import('./src/components/org/OrgDatatable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForUsers: typeof import('./src/components/admin/add/subviews/SearchForUsers.vue')['default']
    SearchUser: typeof import('./src/components/user/SearchUser.vue')['default']
    SelectUser: typeof import('./src/components/admin/add/subviews/SelectUser.vue')['default']
    SimpleBadge: typeof import('./src/components/widgets/SimpleBadge.vue')['default']
    SimpleCard: typeof import('./src/components/widgets/cards/SimpleCard.vue')['default']
    TheCurrentNamespace: typeof import('./src/components/namespace/TheCurrentNamespace.vue')['default']
    TheLogin: typeof import('./src/components/TheLogin.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheTopbar: typeof import('./src/components/TheTopbar.vue')['default']
    UserDatatable: typeof import('./src/components/user/UserDatatable.vue')['default']
    UserGroupsInfo: typeof import('./src/components/user/UserGroupsInfo.vue')['default']
  }
}

export { }
