// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/widgets/ActionButton.vue')['default']
    AddNamespace: typeof import('./src/components/namespace/AddNamespace.vue')['default']
    CardsGrid: typeof import('./src/components/widgets/cards/CardsGrid.vue')['default']
    EditTokenTtl: typeof import('./src/components/namespace/EditTokenTtl.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IAntDesign:saveOutlined': typeof import('~icons/ant-design/save-outlined')['default']
    IClaritySettingsLine: typeof import('~icons/clarity/settings-line')['default']
    IdRenderer: typeof import('./src/components/table/IdRenderer.vue')['default']
    IFluentSettings32Regular: typeof import('~icons/fluent/settings32-regular')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    'ILineMd:cancel': typeof import('~icons/line-md/cancel')['default']
    'IMdi:clockEditOutline': typeof import('~icons/mdi/clock-edit-outline')['default']
    'IMdi:clockOutline': typeof import('~icons/mdi/clock-outline')['default']
    'IMdi:progressClock': typeof import('~icons/mdi/progress-clock')['default']
    'ISiGlyph:signOut': typeof import('~icons/si-glyph/sign-out')['default']
    NamespaceDatatable: typeof import('./src/components/namespace/NamespaceDatatable.vue')['default']
    NamespaceInfo: typeof import('./src/components/namespace/NamespaceInfo.vue')['default']
    SimpleBadge: typeof import('./src/components/widgets/SimpleBadge.vue')['default']
    SimpleCard: typeof import('./src/components/widgets/cards/SimpleCard.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLogin: typeof import('./src/components/TheLogin.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheTopbar: typeof import('./src/components/TheTopbar.vue')['default']
  }
}

export { }
