// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/widgets/ActionButton.vue')['default']
    AddNamespace: typeof import('./src/components/namespace/AddNamespace.vue')['default']
    CardsGrid: typeof import('./src/components/widgets/cards/CardsGrid.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IClaritySettingsLine: typeof import('~icons/clarity/settings-line')['default']
    IdRenderer: typeof import('./src/components/table/IdRenderer.vue')['default']
    IFluentSettings32Regular: typeof import('~icons/fluent/settings32-regular')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    NamespaceDatatable: typeof import('./src/components/namespace/NamespaceDatatable.vue')['default']
    SimpleCard: typeof import('./src/components/widgets/cards/SimpleCard.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLogin: typeof import('./src/components/TheLogin.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheTopbar: typeof import('./src/components/TheTopbar.vue')['default']
  }
}

export { }
